version: '3'
services:
  backend:
    build: ./backend
    container_name: discord-wrapped-backend
  frontend:
    build: ./frontend
    container_name: discord-wrapped-backend

networks:
  default:
    external: true
    name: proxy
    
